// SkillEnums.js

export const CommunicationSkills = {
    EXCELLENT: 'EXCELLENT',
    GOOD: 'GOOD',
    AVERAGE: 'AVERAGE',
    POOR: 'POOR',
    VERBAL: 'VERBAL',
    NON_VERBAL: 'NON_VERBAL',
    LISTENING: 'LISTENING',
    WRITING: 'WRITING',
    PRESENTATION: 'PRESENTATION',
    NEGOTIATION: 'NEGOTIATION'
};

export const TechnicalSkills = {
    DATABASE_MANAGEMENT: 'DATABASE_MANAGEMENT',
    CLOUD_COMPUTING: 'CLOUD_COMPUTING',
    MACHINE_LEARNING: 'MACHINE_LEARNING',
    DATA_ANALYSIS: 'DATA_ANALYSIS',
    SOFTWARE_DEVELOPMENT: 'SOFTWARE_DEVELOPMENT',
    WEB_DEVELOPMENT: 'WEB_DEVELOPMENT',
    SYSTEM_ARCHITECTURE: 'SYSTEM_ARCHITECTURE',
    NETWORK_SECURITY: 'NETWORK_SECURITY',
    DEVOPS: 'DEVOPS',
    UI_UX_DESIGN: 'UI_UX_DESIGN'
};

export const SoftSkills = {
    TEAMWORK: 'TEAMWORK',
    LEADERSHIP: 'LEADERSHIP',
    COMMUNICATION: 'COMMUNICATION',
    PROBLEM_SOLVING: 'PROBLEM_SOLVING',
};

export const ProgrammingLanguage = {
    JAVA: 'JAVA',
    PYTHON: 'PYTHON',
    JAVASCRIPT: 'JAVASCRIPT',
    C: 'C',
    C_PLUS_PLUS: 'C_PLUS_PLUS',
    C_SHARP: 'C_SHARP',
    RUBY: 'RUBY',
    SWIFT: 'SWIFT',
    KOTLIN: 'KOTLIN',
    GO: 'GO',
    TYPESCRIPT: 'TYPESCRIPT',
    PHP: 'PHP',
    RUST: 'RUST',
    SCALA: 'SCALA',
    R: 'R',
    SHELL: 'SHELL',
    OBJECTIVE_C: 'OBJECTIVE_C',
    SQL: 'SQL',
    HTML: 'HTML',
    CSS: 'CSS',
    RUBY_ON_RAILS: 'RUBY_ON_RAILS',
    DJANGO: 'DJANGO',
    SPRING: 'SPRING',
    ANGULAR: 'ANGULAR',
    REACT: 'REACT',
    VUE: 'VUE',
    EMBER: 'EMBER',
    BACKBONE: 'BACKBONE',
    EXPRESS: 'EXPRESS',
    FLASK: 'FLASK',
    LARAVEL: 'LARAVEL',
    SYMFONY: 'SYMFONY',
    CODEIGNITER: 'CODEIGNITER',
    PLAY: 'PLAY',
    SPARK: 'SPARK',
    HIBERNATE: 'HIBERNATE',
    MYBATIS: 'MYBATIS',
    SPRING_BOOT: 'SPRING_BOOT',
    NODE_JS: 'NODE_JS'
};